name: smart_student_assistant_rags
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0 # utilisÃ© seulement en interne
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  http: ^1.2.0
  url_launcher: ^6.2.6
  latlong2: ^0.9.1
  flutter_map: ^6.1.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.10.4
  retrofit_generator: ^10.2.0
  json_serializable: 6.11.3
  flutter_lints: ^5.0.0
  comments_remover: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - images/sekiro.jpg
    - images/ecole-image.jpg
